/**
 * This code was generated by Builder.io.
 */
import React from "react";
import styled from "styled-components";

function CallToAction() {
  const handleClick = () => {
    console.log("CTA button clicked");
  };

  return (
    <CTAWrapper>
      <CTAButton onClick={handleClick} tabIndex="0" role="button">
        TRY ME OUT
        <br />
      </CTAButton>
    </CTAWrapper>
  );
}

const CTAWrapper = styled.div`
  display: flex;
  justify-content: center;
  width: 100%;
  margin-top: 84px;
  @media (max-width: 991px) {
    margin-top: 40px;
  }
`;

const CTAButton = styled.div`
  border-radius: 20px;
  background-color: #92dfbe;
  width: 300px;
  max-width: 100%;
  color: #ffffff;
  text-align: center;
  padding: 34px 70px;
  font: 400 24px Josefin Sans, sans-serif;
  cursor: pointer;
  transition: background-color 0.3s ease;
  &:hover {
    background-color: #7ac9a8;
  }
  &:focus {
    outline: none;
    box-shadow: 0 0 0 3px rgba(146, 223, 190, 0.5);
  }
  @media (max-width: 991px) {
    padding: 20px;
  }
`;

export default CallToAction;
