/**
 * This code was generated by Builder.io.
 */
import React from "react";
import styled from "styled-components";
import { Link } from "react-router-dom";

function CallToAction() {

  return (
    <CTAWrapper>
      <StyledLink to="/toolkit">
        <CTAButton tabIndex="0" role="button">TRY ME OUT</CTAButton>
      </StyledLink>
    </CTAWrapper>
  );
}

const CTAWrapper = styled.div`
  display: flex;
  justify-content: center;
  width: 100%;
  margin-top: 60px;
`;

const CTAButton = styled.div`
  border-radius: 20px;
  background-color: #92dfbe;
  width: 300px;
  max-width: 100%;
  color: #ffffff;
  text-align: center;
  padding: 20px;
  font: 400 24px Josefin Sans, sans-serif;
  cursor: pointer;
  transition: background-color 0.3s ease;
  &:hover {
    background-color: #7ac9a8;
  }
  &:focus {
    outline: none;
    box-shadow: 0 0 0 3px rgba(146, 223, 190, 0.5);
  }
  @media (max-width: 991px) {
    font-size: 20px;
    padding: 15px;
  }
`;

const StyledLink = styled(Link)`
text-decoration: none;
`

export default CallToAction;
