/**
 * This code was generated by Builder.io.
 */
import React from "react";
import styled from "styled-components";
import Header from "./Header";
import Navigation from "./Navigation";
import IntroSection from "./IntroSection";
import CallToAction from "./CallToAction";

function EmpowerHerKit() {
  return (
    <HomeFrame>
      <Header />
      <Navigation />
      <main>
        <IntroSection />
        <CallToAction />
      </main>
    </HomeFrame>
  );
}

const HomeFrame = styled.div`
  background-color: #dcd4c7;
  display: flex;
  flex-direction: column;
  align-items: center;
  overflow: hidden;
  padding: 51px 0 96px;
`;

export default EmpowerHerKit;
