/**
 * This code was generated by Builder.io.
 */
import React from "react";
import styled from "styled-components";

function Header() {
  return <Title>EmpowerHer Kit</Title>;
}

const Title = styled.h1`
  color: #06423d;
  font: 400 80px Josefin Sans, sans-serif;
  text-align: center;
  margin: 0 0 20px;
  @media (max-width: 991px) {
    font-size: 40px;
  }
`;

export default Header;
