/**
 * This code was generated by Builder.io.
 */
import React from "react";
import styled from "styled-components";

function IntroSection() {
  return (
    <Section>
      <ContentWrapper>
        <ImageColumn>
          <Img
            loading="lazy"
            src="https://cdn.builder.io/api/v1/image/assets/TEMP/d87734c4b84b89fd17f4ece22b07963a9ec55e349c5faecd5b1db5696a2f2b48?placeholderIfAbsent=true&apiKey=e971e203cde84a8aa1211a90faf2b36b"
            alt="EmpowerHer Kit illustration"
          />
        </ImageColumn>
        <TextColumn>
          <TextContent>
            <IntroTitle>What is the EmpowerHer Kit?</IntroTitle>
            <IntroParagraph>
              Quartet Solutions has provided a web-based toolkit beneficial to
              those who need assistance in a variety of leadership skills and
              resources. The EmpowerHer Kit was inspired to enhance the journey
              of women in leadership by creating a user-friendly tool that can
              create an environment for a straightforward approach to leadership
              development.
            </IntroParagraph>
          </TextContent>
        </TextColumn>
      </ContentWrapper>
    </Section>
  );
}

const Section = styled.section`
  display: flex;
  margin-top: 80px;
  width: 100%;
  flex-direction: column;
  padding: 0 62px;
  @media (max-width: 991px) {
    margin-top: 40px;
    padding: 0 20px;
  }
`;

const ContentWrapper = styled.div`
  gap: 20px;
  display: flex;
  @media (max-width: 991px) {
    flex-direction: column;
    align-items: stretch;
    gap: 0px;
  }
`;

const ImageColumn = styled.div`
  display: flex;
  flex-direction: column;
  line-height: normal;
  width: 50%;
  margin-left: 0px;
  @media (max-width: 991px) {
    width: 100%;
  }
`;

const Img = styled.img`
  aspect-ratio: 1.34;
  object-fit: contain;
  object-position: center;
  width: 100%;
  flex-grow: 1;
  @media (max-width: 991px) {
    max-width: 100%;
    margin-top: 40px;
  }
`;

const TextColumn = styled.div`
  display: flex;
  flex-direction: column;
  line-height: normal;
  width: 50%;
  margin-left: 20px;
  @media (max-width: 991px) {
    width: 100%;
  }
`;

const TextContent = styled.div`
  display: flex;
  flex-direction: column;
  align-self: stretch;
  font-family: Josefin Sans, sans-serif;
  color: #06423d;
  margin: auto 0;
  @media (max-width: 991px) {
    margin-top: 40px;
  }
`;

const IntroTitle = styled.h2`
  font-size: 36px;
  font-weight: 700;
  text-align: center;
  align-self: center;
  margin-left: 23px;
  @media (max-width: 991px) {
    max-width: 100%;
  }
`;

const IntroParagraph = styled.p`
  font-size: 32px;
  font-weight: 500;
  margin-top: 45px;
  @media (max-width: 991px) {
    margin-top: 40px;
  }
`;

export default IntroSection;
