/**
 * This code was generated by Builder.io.
 */
import React from "react";
import styled from "styled-components";

function IntroSection() {
  return (
    <Section>
      <ContentWrapper>
        <ImageColumn>
          <Img
            loading="lazy"
            src="https://cdn.builder.io/api/v1/image/assets/TEMP/d87734c4b84b89fd17f4ece22b07963a9ec55e349c5faecd5b1db5696a2f2b48?placeholderIfAbsent=true&apiKey=e971e203cde84a8aa1211a90faf2b36b"
            alt="EmpowerHer Kit illustration"
          />
        </ImageColumn>
        <TextColumn>
          <TextContent>
            <IntroTitle>What is the EmpowerHer Kit?</IntroTitle>
            <IntroParagraph>
              Quartet Solutions has provided a web-based toolkit beneficial to
              those who need assistance in a variety of leadership skills and
              resources. The EmpowerHer Kit was inspired to enhance the journey
              of women in leadership by creating a user-friendly tool that can
              create an environment for a straightforward approach to leadership
              development.
            </IntroParagraph>
          </TextContent>
        </TextColumn>
      </ContentWrapper>
    </Section>
  );
}

const Section = styled.section`
  display: flex;
  width: 100%;
  max-width: 1200px;
  margin: 0 auto;
  padding: 0 20px;
  box-sizing: border-box;
`;

const ContentWrapper = styled.div`
  display: flex;
  gap: 40px;
  align-items: center;
  @media (max-width: 991px) {
    flex-direction: column;
    align-items: stretch;
    gap: 20px;
  }
`;

const ImageColumn = styled.div`
  flex: 1;
`;

const Img = styled.img`
  width: 100%;
  height: auto;
  object-fit: contain;
`;

const TextColumn = styled.div`
  flex: 1;
`;

const TextContent = styled.div`
  font-family: Josefin Sans, sans-serif;
  color: #06423d;
`;

const IntroTitle = styled.h2`
  font-size: 36px;
  font-weight: 700;
  text-align: center;
  margin-bottom: 20px;
  @media (max-width: 991px) {
    font-size: 28px;
  }
`;

const IntroParagraph = styled.p`
  font-size: 18px;
  font-weight: 500;
  line-height: 1.6;
  @media (max-width: 991px) {
    font-size: 16px;
  }
`;

export default IntroSection;
