/**
 * This code was generated by Builder.io.
 */
import React from "react";
import styled from "styled-components";

function Navigation() {
  const navItems = ["Home", "Toolkit", "About Us"];

  return (
    <NavContainer>
      <NavBar />
      <NavList>
        {navItems.map((item, index) => (
          <NavItem key={index}>{item}</NavItem>
        ))}
      </NavList>
    </NavContainer>
  );
}

const NavContainer = styled.nav`
  position: relative;
  width: 100%;
  max-width: 1826px;
  margin: 0 auto 40px;
`;

const NavBar = styled.div`
  border-radius: 20px;
  background-color: #92dfbe;
  width: 100%;
  height: 20px;
`;

const NavList = styled.ul`
  position: absolute;
  top: calc(100% + 10px);
  right: 0;
  display: flex;
  gap: 20px;
  color: #06423d;
  font: 400 20px Josefin Sans, sans-serif;
  list-style-type: none;
  padding: 0;
  margin: 0;
  @media (max-width: 991px) {
    right: 10px;
  }
`;

const NavItem = styled.li`
  white-space: nowrap;
  cursor: pointer;
  @media (max-width: 991px) {
    white-space: initial;
  }
`;

export default Navigation;
