/**
 * This code was generated by Builder.io.
 */
import React from "react";
import styled from "styled-components";

function Header() {
  return <HeaderTitle>EmpowerHer Kit</HeaderTitle>;
}

const HeaderTitle = styled.h1`
  color: #06423d;
  font: 80px Josefin Sans, sans-serif;
  text-align: center;
  @media (max-width: 991px) {
    max-width: 100%;
    font-size: 40px;
  }
`;

export default Header;
