/**
 * This code was generated by Builder.io.
 */
import React from "react";
import styled from "styled-components";

function ToolboxInstructions() {
  return (
    <Instructions>
      To start please click on the toolbox icon.
    </Instructions>
  );
}

const Instructions = styled.p`
  color: #000;
  font: 24px Inter, sans-serif;
  text-align: center;
  margin-bottom: 40px;
  @media (max-width: 991px) {
    font-size: 20px;
    margin-bottom: 20px;
  }
`;

export default ToolboxInstructions;