/**
 * This code was generated by Builder.io.
 */
import React from "react";
import styled from "styled-components";
import ToolBoxIcon from '../../../../assets/toolbox-svgrepo-com (1).svg';

function ToolboxIcon({ active }) {
  return (
    <IconWrapper $active={active}>
      <IconBackground />
      <IconSVG $active={active} src={ToolBoxIcon} alt="Toolbox Icon" />
    </IconWrapper>
  );
}

const IconWrapper = styled.div`
  position: relative;
  display: flex;
  justify-content: center;
  align-items: center;
  width: 300px;
  height: 300px;
  color: ${props => props.$active ? "#F2C758" : "#000000"};
  transition: color 0.3s ease, transform 0.3s ease;
  z-index: 1; /* Ensure the wrapper and its contents are above the background */
  &:hover {
    transform: scale(1.05);
  }
`;

const IconBackground = styled.div`
  position: absolute;
  width: 600px;
  height: 300px;
  bottom: 0;
  background-color: #92dfbe;
  border-top-left-radius: 300px;
  border-top-right-radius: 300px;
  z-index: 0;
`;

const IconSVG = styled.img`
  height: 200px;
  position: relative;
  z-index: 1; /* Ensure the SVG is above the background */
  filter: ${props => props.$active ? "invert(93%) sepia(56%) saturate(3886%) hue-rotate(316deg) brightness(105%) contrast(90%);" : "none"};
`;

export default ToolboxIcon;
