/**
 * This code was generated by Builder.io.
 */
import React from "react";
import styled from "styled-components";

function ContentSection(props) {
  const { tabContent, index } = props;

  console.log('tab content' + tabContent)

  return (
    <ContentWrapper>
      <ContentColumns>
        <DescriptionColumn>
          <Description>
            {tabContent[index].description}
          </Description>
        </DescriptionColumn>
        <ResourcesColumn>
          <ResourcesBackground>
            <ScrollableContent>
              <ResourceTitle>{tabContent[index].title}</ResourceTitle>
              <ResourceText>
                Knowing how to negotiate can help you get the pay you feel you
                deserve click the links below for tips on how to negotiate.
                <ResourceLink
                  href="https://www.pon.harvard.edu/daily/salary-negotiations/negotiate-salary-3-winning-strategies/"
                  target="_blank"
                  rel="noopener noreferrer"
                >
                  3 Salary Negotiation Tips
                </ResourceLink>
                <ResourceLink
                  href="https://www.pon.harvard.edu/freemium/teaching-negotiation-understanding-the-impact-of-role-play-simulations/"
                  target="_blank"
                  rel="noopener noreferrer"
                >
                  Teaching Negotiation
                </ResourceLink>
                Preparation, Investigation, and Roleplaying are three tips women
                should grasp to help level the playing field in the negotiation
                world. This article provides an brief dive of six tips that can
                place women in different tax brackets (Harvard, 2024). Using the
                article below, pick a tip that you may not have been aware of
                and think about how it would benefit you.
                <ResourceLink
                  href="https://www.pon.harvard.edu/daily/salary-negotiations/salary-negotiation-skills-different-for-men-and-women/"
                  target="_blank"
                  rel="noopener noreferrer"
                >
                  Are Salary Negotiation Skills Different for Men and Women?
                </ResourceLink>
              </ResourceText>
            </ScrollableContent>
          </ResourcesBackground>
        </ResourcesColumn>
      </ContentColumns>
    </ContentWrapper>
  );
}

const ContentWrapper = styled.section`
  background-color: #d9d9d9;
  padding: 60px 50px;
  @media (max-width: 991px) {
    max-width: 100%;
    padding: 0 20px;
  }
`;

const ContentColumns = styled.div`
  gap: 10%;
  display: flex;
  @media (max-width: 991px) {
    flex-direction: column;
    align-items: stretch;
    gap: 30px;
  }
`;

const DescriptionColumn = styled.div`
  display: flex;
  flex-direction: column;
  line-height: normal;
  width: 35%;
  margin-left: 0px;
  @media (max-width: 991px) {
    width: 100%;
  }
`;

const Description = styled.p`
  background-color: #ffffff;
  align-self: stretch;
  color: #000000;
  text-align: center;
  max-width: 100%;
  margin: auto 0;
  padding: 40px 30px 90px;
  font: 400 24px Josefin Sans, sans-serif;
  @media (max-width: 991px) {
    max-width: 100%;
    margin-top: 30px;
    padding: 0 20px 80px;
  }
`;

const ResourcesColumn = styled.div`
  display: flex;
  flex-direction: column;
  line-height: normal;
  width: 55%;
  margin-left: 20px;
  @media (max-width: 991px) {
    width: 100%;
    margin-left: 0;
  }
`;

const ResourcesBackground = styled.div`
  background-color: #ffffff;
  display: flex;
  flex-grow: 1;
  flex-direction: column;
  font-family: Josefin Sans, sans-serif;
  color: #06423d;
  font-weight: 400;
  text-align: center;
  width: 100%;
  padding: 30px 7px 0;
  @media (max-width: 991px) {
    max-width: 100%;
    margin-top: 30px;
  }
`;

const ScrollableContent = styled.div`
  background-color: #ffffff;
  z-index: 10;
  display: flex;
  min-height: 100px;
  flex-direction: column;
  overflow-y: auto;
  align-items: center;
  justify-content: start;
  padding: 35px 40px 90px;
  @media (max-width: 991px) {
    max-width: 100%;
    padding: 0 20px 80px;
  }
`;

const ResourceTitle = styled.h2`
  font-size: 28px;
  @media (max-width: 991px) {
    max-width: 100%;
  }
`;

const ResourceText = styled.p`
  font-size: 16px;
  margin-top: 40px;
  @media (max-width: 991px) {
    max-width: 100%;
    margin-top: 30px;
  }
`;

const ResourceLink = styled.a`
  display: block;
  margin: 10px 0;
  color: #06423d;
  text-decoration: underline;
`;

export default ContentSection;