/**
 * This code was generated by Builder.io.
 */
import React from "react";
import styled from "styled-components";
import NavBar from "./NavBar";
import ToolkitSection from "./ToolkitSection";
import SalaryResources from "./SalaryResources";

function EmpowerHerKit() {
  return (
    <MainContainer>
      <Header>EmpowerHer Kit</Header>
      <NavBar />
      <ToolkitSection />
      <SalaryResources />
    </MainContainer>
  );
}

const MainContainer = styled.main`
  background-color: #dcd4c7;
  display: flex;
  flex-direction: column;
  overflow: hidden;
  padding: 55px 0;
`;

const Header = styled.h1`
  color: #06423d;
  align-self: center;
  font: 400 80px Josefin Sans, sans-serif;
  @media (max-width: 991px) {
    max-width: 100%;
    font-size: 40px;
  }
`;

export default EmpowerHerKit;