/**
 * This code was generated by Builder.io.
 */
import React, { useState } from "react";
import styled from "styled-components";
import ToolkitTabs from "./ToolkitTabs";
import ContentSection from "./ContentSection";
import Header from "../../../EmpowerHerKit/Header";
import Navigation from "../../../EmpowerHerKit/Navigation";





function EmpowerHerKit(props) {
  const { activeBucket } = props;
  const tabs = activeBucket.tabs
  const [activeTab, setActiveTab] = useState({tabName: tabs[0], index: 0});

  
  const tabContent = activeBucket['tabContent']

  console.log(activeBucket['tabContent'])


  return (
    <StyledMain>
      <Header />
      <Navigation />
      <ToolkitTabs tabs={tabs} setActiveTab={setActiveTab} activeTab={activeTab}/>
      <ContentSection tabContent={tabContent} index={activeTab.index}/>
    </StyledMain>
  );
}

const StyledMain = styled.main`
  background-color: #dcd4c7;
  display: flex;
  flex-direction: column;
  overflow: hidden;
  padding: 55px 0;
`;

export default EmpowerHerKit;