/**
 * This code was generated by Builder.io.
 */
import React from "react";
import styled from "styled-components";
import ToolkitTabs from "./ToolkitTabs";
import ContentSection from "./ContentSection";
import Header from "../../../EmpowerHerKit/Header";
import Navigation from "../../../EmpowerHerKit/Navigation";


function EmpowerHerKit() {
  return (
    <StyledMain>
      <Header />
      <Navigation />
      <ToolkitTabs />
      <ContentSection />
    </StyledMain>
  );
}

const StyledMain = styled.main`
  background-color: #dcd4c7;
  display: flex;
  flex-direction: column;
  overflow: hidden;
  padding: 55px 0;
`;

export default EmpowerHerKit;