/**
 * This code was generated by Builder.io.
 */
import React from "react";
import styled from "styled-components";

function NavBar() {
  return (
    <NavWrapper>
      <NavMenu>
        <NavLink>Home</NavLink>
        <NavLink>Toolkit</NavLink>
        <NavLink>About Us</NavLink>
      </NavMenu>
    </NavWrapper>
  );
}

const NavWrapper = styled.nav`
  border-radius: 20px;
  background-color: #92dfbe;
  align-self: center;
  display: flex;
  width: 90%;
  max-width: 1600px;
  height: 20px;
  margin-bottom: 30px;
`;

const NavMenu = styled.ul`
  align-self: end;
  display: flex;
  width: 250px;
  max-width: 100%;
  gap: 20px;
  color: #06423d;
  justify-content: space-between;
  margin: 14px 60px 0 0;
  font: 400 16px Josefin Sans, sans-serif;
  list-style-type: none;
  padding: 0;
  @media (max-width: 991px) {
    margin-right: 10px;
  }
`;

const NavLink = styled.li`
  white-space: nowrap;
  cursor: pointer;
  @media (max-width: 991px) {
    white-space: initial;
  }
`;

export default NavBar;