/**
 * This code was generated by Builder.io.
 */
import React from "react";
import styled from "styled-components";

function NavBar() {
  return (
    <Nav>
      <NavList>
        <NavItem>Home</NavItem>
        <NavItem>Toolkit</NavItem>
        <NavItem>About Us</NavItem>
      </NavList>
    </Nav>
  );
}

const Nav = styled.nav`
  border-radius: 20px;
  background-color: #92dfbe;
  align-self: center;
  display: flex;
  width: 1826px;
  max-width: 100%;
  height: 20px;
`;

const NavList = styled.ul`
  display: flex;
  width: 301px;
  max-width: 100%;
  gap: 20px;
  color: #06423d;
  justify-content: space-between;
  margin: 14px 81px 0 auto;
  font: 400 20px Josefin Sans, sans-serif;
  list-style-type: none;
  padding: 0;
  @media (max-width: 991px) {
    margin-right: 10px;
  }
`;

const NavItem = styled.li`
  white-space: nowrap;
  @media (max-width: 991px) {
    white-space: initial;
  }
`;

export default NavBar;