/**
 * This code was generated by Builder.io.
 */
import React from "react";
import styled from "styled-components";

function SalaryResources() {
  return (
    <ResourcesContainer>
      <ResourcesContent>
        <InfoColumn>
          <InfoText>
            It is very crucial in today's world that you know how to navigate and find valuable information on expected pay for the position you are interested in. Glassdoor is a great resource to search salaries in different industries
          </InfoText>
        </InfoColumn>
        <ResourcesColumn>
          <ResourcesBackground>
            <ScrollableContent>
              <ResourcesTitle>Market Salary Resources</ResourcesTitle>
              <ResourcesDescription>
                It's difficult to know whether you're being compensated fairly or not, using the resources below allows you to put more energy to other needs in your life.
                <br /><br />
                <ResourceLink href="https://www.bls.gov/" target="_blank" rel="noopener noreferrer">
                  Bureau of Labor Statistics
                </ResourceLink>
                <br /><br />
                Glassdoor is a great resource to search salaries in different industries. Search for your current or prospective roles to see if you're getting the average salary according to Glassdoor.
                <br /><br />
                <ResourceLink href="https://www.glassdoor.com/Salaries/index.htm" target="_blank" rel="noopener noreferrer">
                  Glassdoor- Salaries
                </ResourceLink>
              </ResourcesDescription>
            </ScrollableContent>
            <ResourceImage src="https://cdn.builder.io/api/v1/image/assets/TEMP/bf7a7c817da887fd9eee36e005e4406cc46c6c67fc6eb20eee597a95acbc4ae2?placeholderIfAbsent=true&apiKey=e971e203cde84a8aa1211a90faf2b36b" alt="Resource illustration" />
          </ResourcesBackground>
        </ResourcesColumn>
      </ResourcesContent>
    </ResourcesContainer>
  );
}

const ResourcesContainer = styled.section`
  background-color: #d9d9d9;
  padding: 82px 65px;
  @media (max-width: 991px) {
    max-width: 100%;
    padding: 0 20px;
  }
`;

const ResourcesContent = styled.div`
  display: flex;
  gap: 20px;
  @media (max-width: 991px) {
    flex-direction: column;
    align-items: stretch;
    gap: 0;
  }
`;

const InfoColumn = styled.div`
  display: flex;
  flex-direction: column;
  line-height: normal;
  width: 45%;
  margin-left: 0;
  @media (max-width: 991px) {
    width: 100%;
  }
`;

const InfoText = styled.p`
  background-color: #fff;
  color: #000;
  text-align: center;
  width: 100%;
  margin: auto 0;
  padding: 59px 44px 158px;
  font: 400 35px Josefin Sans, sans-serif;
  @media (max-width: 991px) {
    max-width: 100%;
    margin-top: 40px;
    padding: 0 20px 100px;
  }
`;

const ResourcesColumn = styled.div`
  display: flex;
  flex-direction: column;
  line-height: normal;
  width: 55%;
  margin-left: 20px;
  @media (max-width: 991px) {
    width: 100%;
  }
`;

const ResourcesBackground = styled.div`
  background-color: #fff;
  display: flex;
  flex-grow: 1;
  flex-direction: column;
  font-family: Josefin Sans, sans-serif;
  color: #06423d;
  font-weight: 400;
  text-align: center;
  width: 100%;
  padding: 12px 7px;
  @media (max-width: 991px) {
    max-width: 100%;
    margin-top: 40px;
  }
`;

const ScrollableContent = styled.div`
  background-color: #fff;
  display: flex;
  min-height: 800px;
  flex-direction: column;
  overflow: hidden;
  align-items: center;
  justify-content: start;
  padding: 45px 49px 344px;
  @media (max-width: 991px) {
    max-width: 100%;
    padding: 0 20px 100px;
  }
`;

const ResourcesTitle = styled.h2`
  font-size: 32px;
  @media (max-width: 991px) {
    max-width: 100%;
  }
`;

const ResourcesDescription = styled.p`
  font-size: 20px;
  margin-top: 58px;
  @media (max-width: 991px) {
    max-width: 100%;
    margin-top: 40px;
  }
`;

const ResourceLink = styled.a`
  color: #06423d;
  text-decoration: underline;
`;

const ResourceImage = styled.img`
  aspect-ratio: 2.87;
  object-fit: contain;
  object-position: center;
  width: 623px;
  align-self: center;
  z-index: 10;
  margin-top: -368px;
  max-width: 100%;
  @media (max-width: 991px) {
    margin-top: -200px;
  }
`;

export default SalaryResources;