/**
 * This code was generated by Builder.io.
 */
import React from "react";
import styled from "styled-components";

function BubbleButton({ imgSrc, alt }) {
  return (
    <BubbleContainer>
      <BubbleImage src={imgSrc} alt={alt} />
    </BubbleContainer>
  );
}

const BubbleContainer = styled.button`
  background-color: #f2c758;
  border-radius: 50%;
  display: flex;
  width: 250px;
  height: 250px;
  align-items: center;
  justify-content: center;
  border: none;
  cursor: pointer;
  padding: 0;
  @media (max-width: 991px) {
    width: 200px;
    height: 200px;
  }
`;

const BubbleImage = styled.img`
  width: 100px;
  height: 100px;
  object-fit: contain;
  @media (max-width: 991px) {
    width: 80px;
    height: 80px;
  }
`;

export default BubbleButton;