/**
 * This code was generated by Builder.io.
 */
import React from "react";
import styled from "styled-components";
import BubbleButton from "./BubbleButton";
import Header from "../../../../EmpowerHerKit/Header";
import Navigation from "../../../../EmpowerHerKit/Navigation";

function EmpowerHerKit(props) {
  const { onClick } = props
  return (
    <ToolkitFrame>
      <Header />
      <Navigation />
      <main>
        <ContentWrapper onClick={() => onClick()}>
          <CentralBubble>
            <BubbleButton imgSrc="https://cdn.builder.io/api/v1/image/assets/TEMP/e22edac89925935e17c8009adcf7162c4573d8caf00eccf46be60336d546a938?placeholderIfAbsent=true&apiKey=e971e203cde84a8aa1211a90faf2b36b" alt="Central bubble icon" />
          </CentralBubble>
          <ButtonsContainer>
            <BubbleButton imgSrc="https://cdn.builder.io/api/v1/image/assets/TEMP/1a4fc143316982af236a87bbf3d3c669c80c35a1a7c5e31e502d8f421b07051a?placeholderIfAbsent=true&apiKey=e971e203cde84a8aa1211a90faf2b36b" alt="Equal pay button icon" />
            <CentralImage src="https://cdn.builder.io/api/v1/image/assets/TEMP/5d7a70e149e6698d45f04c441c13397fca49685dfdf43fb653cde34c7559cb96?placeholderIfAbsent=true&apiKey=e971e203cde84a8aa1211a90faf2b36b" alt="Central decorative image" />
            <BubbleButton imgSrc="https://cdn.builder.io/api/v1/image/assets/TEMP/68bf430f724a904a2c41a06660e71c2e60ae382155f35b1e24af90b43c67674a?placeholderIfAbsent=true&apiKey=e971e203cde84a8aa1211a90faf2b36b" alt="Family button icon" />
          </ButtonsContainer>
        </ContentWrapper>
      </main>
    </ToolkitFrame>
  );
}

const ToolkitFrame = styled.div`
  background-color: #dcd4c7;
  display: flex;
  flex-direction: column;
  overflow: hidden;
  padding: 51px 47px 0;
  @media (max-width: 991px) {
    padding: 0 20px;
  }
`;

const Title = styled.h1`
  color: #06423d;
  align-self: center;
  font: 400 80px Josefin Sans, sans-serif;
  @media (max-width: 991px) {
    max-width: 100%;
    font-size: 40px;
  }
`;

const ContentWrapper = styled.div`
  align-self: end;
  display: flex;
  width: 100%;
  max-width: 1454px;
  flex-direction: column;
  margin: 14px 34px 0 0;
  @media (max-width: 991px) {
    max-width: 100%;
    margin-right: 10px;
  }
`;

const Navigation = styled.nav`
  align-self: end;
  display: flex;
  width: 301px;
  max-width: 100%;
  gap: 20px;
  justify-content: space-between;
`;

const NavLink = styled.a`
  color: #06423d;
  font: 400 20px Josefin Sans, sans-serif;
  text-decoration: none;
  cursor: pointer;
  @media (max-width: 991px) {
    white-space: initial;
  }
`;

const CentralBubble = styled.div`
  align-self: center;
  margin-top: 260px;
  @media (max-width: 991px) {
    margin-top: 40px;
  }
`;

const ButtonsContainer = styled.div`
  width: 1150px;
  max-width: 100%;
  display: flex;
  justify-content: space-between;
  align-items: center;
  @media (max-width: 991px) {
    flex-direction: column;
    align-items: stretch;
  }
`;

const CentralImage = styled.img`
  aspect-ratio: 2;
  object-fit: contain;
  object-position: center;
  width: 57%;
  margin-top: 60px;
  @media (max-width: 991px) {
    width: 100%;
    max-width: 100%;
    margin-top: 40px;
  }
`;

export default EmpowerHerKit;