/**
 * This code was generated by Builder.io.
 */
import React from "react";
import styled from "styled-components";

function NavBar() {
  return <NavBarContainer />;
}

const NavBarContainer = styled.div`
  border-radius: 20px;
  background-color: #92dfbe;
  display: flex;
  height: 20px;
  @media (max-width: 991px) {
    max-width: 100%;
  }
`;

export default NavBar;